### ISSUE TITLE
CreditNote is not working in dynamic

### ISSUE THREAD

**Issue by petber** [ON-IT/Visma.Net#55]
int contextId = 1234569;
            string token = "your_security_token";
            dynamic vismaNet = new VismaNet(contextId, token);

            //This is working
            var accounts = await vismaNet.Account.All();
            foreach (var account in accounts)
            {
                Console.WriteLine($"{account.accountCD}: {account.description}");
            }

            //Not working
            var allCreditNotes = await vismaNet.CreditNote.All();
            foreach (var creditnote in allCreditNotes)
            {
                Console.WriteLine("{0}: {1}", creditnote.referenceNumber, creditnote.documentType);
            }

//Error message in Visual Studio
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException was unhandled
Message: An unhandled exception of type 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' occurred in mscorlib.dll
Additional information: System.Collections.Generic.List<ONIT.VismaNetApi.Models.CreditNote> innehåller ingen definition för GetAwaiter

**Comment by fredrikjacobson** [comment]
The method is not Async yet as there is not "GetAwaiter". Try removing await in the line:
 var allCreditNotes = **await** vismaNet.CreditNote.All();

**Comment by omelhus** [comment]
How bout we change all the legacy methods now, so that we'll get consistency between the dynamic and the typed endpoints? This will eliminate this kind of problems.

**Comment by Aztherion** [comment]
Actually, the reason to why 

var accounts = await vismaNet.Account.All();

works is because of a typo. There is not "Account"-property in the VismaNet class. The actual naming is Accounts. Long story short; the call actually ends up in the async method because of the typo. 

Since there is a property called CreditNote in the VismaNet class, the call to CreditNote.All() will end up in the legacy method thus prompting the missing GetAwaiter-error. 

If you rename the CreditNote property in VismaNet.cs to CreditNotes and run the above code again it will actually work. 

Equally, calling Accounts.All() with await will result in the same error as calling CreditNote.All() does. 

@fredrikjacobson is correct though.. Since CreditNote is a valid property name then it should be called without "await" even when using dynamic.

**Comment by omelhus** [comment]
This is now solved as all the endpoints are renamed to be consistent with the API, and the AsyncTask suffix is removed from the typed implementation methods.
